### PR TITLE
Implementing backspace deletion

### PR DESCRIPTION
**Pull request by chb1828**
This time, I implemented backspace deletion. 
It's the desired feature that tags gets deleted when you press backspace button.
but flutter doesn`t have the function to detect the soft backspace button.
So I did the trick like the space add function.
Execute when the param value of onChanged function enters once space.
Since this part can conflict with the space add-in, the form's starting value is always two spaces.
When the TextField focuses, it is always fixed with two spaces to avoid errors in the user's space position via focusNode.
The problem here occurs when the user forcibly moves the cursor of the textfield.
However, I thought that people would seldom deliberately change the position of the cursor.
Below is a demo video.

test

I'm sorry for my poor English.
Please let me know if there is any problem with the code.

### CODE REVIEW

**Comment by wonjae-codecabin** [comment]
@eyoeldefare  This is exactly what I am looking for. Do you have any plan to merge this pr?

**Comment by eyoeldefare** [comment]
> @eyoeldefare This is exactly what I am looking for. Do you have any plan to merge this pr?

Hey I will officially start reviewing and maintaining this package starting end of May. I started a new job and was too busy to get into Flutter properly in these past months. I will have to review everything and test everything over end of May. Until then, you can fork and work with the new changes.

**Comment by eyoeldefare** [comment]
hey guys, so I think this defeats the point of the delete button in the tags and introduces more complications that I don't have the time to test and maintain for now. I apologize for that.

Please feel free to fork this and create your own package with those features. Big thanks for the contribution too.

**Comment by 0xNF** [comment]
I don't think this defeats the point at all, but I can't comment to how much extra maintenance burden this would be.

I'd like to see this implemented, if possible.

**Pull request closed without merging**
