### PR TITLE
Optional "allowSpaces" argument to prevent splitting on spaces

### PR DESCRIPTION
**Pull request by Neicul123**
Some of the tags entered in my app require spaces, it would be great if we could support this through an extra argument. I've added an optional argument that defaults to false in order to keep the current behavior by default.

### CODE REVIEW

**Comment by eyoeldefare** [comment]
What's the point of using tags if they have space in them? The point of tags is so they don't have space in them. lol
But since you already know what you want and fixed it too, I think you can just fork repo, and create your package with those features.

**Comment by Neicul123** [comment]
Tags can just as well be "Episode 1", "Chapter 2" or whatever, tags are not always limited to just one word. I already forked it and am using the fork, but I figured others might benefit from it as well in the future.

I don't mind either way.

**Comment by eyoeldefare** [comment]
https://space.stackexchange.com/help/tagging

**Comment by eyoeldefare** [comment]
> 
> 
> Tags can just as well be "Episode 1", "Chapter 2" or whatever, tags are not always limited to just one word. I already forked it and am using the fork, but I figured others might benefit from it as well in the future.
> 
> I don't mind either way.

https://space.stackexchange.com/help/tagging

"Each question may only contain 5 tags at a maximum, so choose the ones that best describe your question. **Spaces are not allowed in tags**..."

**Pull request closed without merging**
