### PR TITLE
Change OutlineInputBorder to InputBorder

### PR DESCRIPTION
**Pull request by Martibis**
This makes it so you can also use UnderlineInputBorder and other InputBorders

### CODE REVIEW

**Comment by eyoeldefare** [comment]
Hey thanks for the work, I will test it soon.

**Comment by eyoeldefare** [comment]
Hey, first of all, `InputBorders` is an abstract class and it can not be instantiated. So, this doesn't really work.

**Comment by Martibis** [comment]
I'm currently running it like this in my code without issue, but for backwards compatibility it might than make sense  to instantiate with a default value (which can remain an OutlineInputBorder as it is now). On my phone now, so not seeing the code atm.

You can't instantiate InputBorder of course. You'd need to Instantiate it as OutlineInputBorder or UnderlineInputBorder or any other type of InputBorder.

**Comment by eyoeldefare** [comment]
Oh I see, its a polymorphism abstract class. I see, I will change it next Saturday. 
Thanks for the heads up.

**Pull request merged**
